# Generated by Django 3.0.2 on 2020-01-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetarck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveSmallIntegerField(null=True)),
                ('end_time', models.PositiveSmallIntegerField(null=True)),
                ('hour_rate', models.IntegerField()),
            ],
        ),
    ]
