# Generated by Django 3.0.2 on 2020-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveSmallIntegerField(null=True)),
                ('end_time', models.PositiveSmallIntegerField(null=True)),
                ('hour_rate', models.IntegerField()),
                ('spent_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Timetarck',
        ),
    ]
