# Generated by Django 3.0.2 on 2020-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200201_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrack',
            name='mul',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
