# Generated by Django 3.0.2 on 2020-02-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_timetrack_mul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrack',
            name='end_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timetrack',
            name='start_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
