# Generated by Django 3.0.2 on 2020-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200203_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracktime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30, null=True)),
                ('end_time', models.CharField(max_length=30)),
                ('hour_rate', models.IntegerField()),
                ('spent_time', models.IntegerField(blank=True, null=True)),
                ('mul', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Timetrack',
        ),
    ]
