# Generated by Django 3.0.2 on 2020-02-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20200204_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='project_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
