# Generated by Django 3.0.2 on 2020-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200204_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='project_name',
        ),
    ]
