# Generated by Django 3.0.2 on 2020-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200204_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('project_details', models.CharField(max_length=300)),
            ],
        ),
    ]
