# Generated by Django 3.0.2 on 2020-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_remove_revenue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
