# Generated by Django 3.0.2 on 2020-02-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_revenue_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='hour_rate',
        ),
        migrations.AlterField(
            model_name='revenue',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Projectform'),
        ),
    ]
